Refine explanations and improve formatting in README.md
P-p-H-d/mlib pull request #115
Opened 2024-02-06 21:14 UTC by derskythe

Hi, Thanks for the library.
For my part, I would like to offer updated documentation.
In my opinion, in this form it is much easier to read and easier to navigate.

What is done:
- [x] Added missing code blocks
- [x] Changing the format of code examples is was neccessary
- [x] Highlighting variable names and macro names in text
- [x] Refining links to section
- [x] Adjusting the indenting of API documentation listings for better readability

2024-02-07 21:24 UTC, P-p-H-d requested changes
Thanks a lot for your huge rework on the documentation!

I tried to perform a review of it and find (few) issues in it I have listed below.
By reading the patch I also found some errors in the original documentation :)

2024-02-07 21:24 UTC, P-p-H-d commented on README.md
> +> (Needs M\*LIB support to clear the skipped objects).
The note is obsolete. Throwing an exception is now supported

The 3 last sentences should be : "The last case is not properly fully supported yet."

2024-02-07 21:24 UTC, P-p-H-d commented on README.md
> +> that only short names are defined in this header which may be
Remove "that"

2024-02-08 07:51 UTC, derskythe commented on README.md
> +_________________
This line is used to further visually separate the chapters

![image](https://github.com/P-p-H-d/mlib/assets/31771569/648dc7ed-d774-4341-acc5-aa78e24c8cfa)

2024-02-08 11:02 UTC, P-p-H-d commented on README.md
> +    LIST_DUAL_PUSH_DEF(list_mpz, mpz_t,                    \
Same remark

2024-02-08 11:02 UTC, P-p-H-d commented on README.md
> +    ARRAY_DEF(array_mpz, mpz_t,                            \
Same remark

2024-02-08 11:02 UTC, P-p-H-d commented on README.md
> +        TUPLE_DEF2(pair,(key_field, string_t, STRING_OPLIST),  \
Same remark

2024-02-08 12:32 UTC, merged